PROCEDURAL LANGUAGE

PROGRAMA - conjunto de instruções que serão executadas

ROTINA - conjunto de instruçoes que executam uma 
função dentro de um programa - um calculo 

SUB - ROTINA - É A APRTE QUE REALIZA UMATAREFA ESPECIFICA EM UM PROGRAMA

PROCEDIMENTOS ARMAZENADOS(STORED PROCEDURES) - SIMILAR A
UMA SUB ROTINA - SERAO EXECUTADOS TODA VEZ QUE UMA
DETERMINADA TAREFA NECESSITE SER REALIZADA.
NÃO RETORNA VALORES

FUNÇÃO (FUNCTIONS) - SIMILAR A PROCEDIMENTOS/SUB ROTINAS
DEVE RETORNAR VALORES

GATILHOS (TRIGGERS) - SIMILARA A PROCEDIMENTOS OU SUB ROTINAS
NAO RETORNA VALORES
É EXECUTADO AUTOMATICAMENTE TODA VEZ QUE UMA
CONDIÇAÕ PRE ESTABELECIDA É SATISFEITA

