- PROCESSOS EQUIVALENTES A SUB ROTINAS
- ARMAZENADOS NO BANCO DE DADOS
- PODEM SER EXECUTADOS A PARTIR DE QUALQUER AMBIENTE 
INTERATIVO COM O BANCO DE DADOS OU SEREM ATIVADAS A 
PARTIR DE LINGUAGENS DE FRONT-END
- DISPONIBILIZADO A PARTIR DA VERSAO 5
- DIFERENÇAS ENTRE PROCEDIEMNTOS E FUNÇOES MUITO SUTIL
RELACIONADO AO ASPECTO FUNCIONAL - STORED PROCEDURES 
PODE NAO RETORNAR VALOR ALGUM


